sdk: "/Users/vidal/code/rhomobile/rhodes"
name: Photos
version: 1.0
vendor: rhomobile
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  codesignidentity:
  entitlements: 