--- 
name: Photos
bbver: 4.6
sdk: /Users/vidal/code/rho_apps/rhodes
applog: rholog.txt
version: 1.0
vendor: rhomobile
iphone: 
  sdk: iphonesimulator4.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
